// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApmimKiG_HwBD7MTVt4TbKaW5enuj6IBE',
    appId: '1:600630814727:web:e346dca8a983cf6af262a2',
    messagingSenderId: '600630814727',
    projectId: 'ic-v1-e1e60',
    authDomain: 'ic-v1-e1e60.firebaseapp.com',
    databaseURL: 'https://ic-v1-e1e60-default-rtdb.firebaseio.com',
    storageBucket: 'ic-v1-e1e60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkqQuEugS5VyJxo443OL1MDgkDEHeoymU',
    appId: '1:600630814727:android:445e07675c8863d7f262a2',
    messagingSenderId: '600630814727',
    projectId: 'ic-v1-e1e60',
    databaseURL: 'https://ic-v1-e1e60-default-rtdb.firebaseio.com',
    storageBucket: 'ic-v1-e1e60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfDtHvt17Q7coECHS20yWxSAOVoN69Xeo',
    appId: '1:600630814727:ios:a240c219444f974cf262a2',
    messagingSenderId: '600630814727',
    projectId: 'ic-v1-e1e60',
    databaseURL: 'https://ic-v1-e1e60-default-rtdb.firebaseio.com',
    storageBucket: 'ic-v1-e1e60.appspot.com',
    iosClientId: '600630814727-jv96eg70s9rpbkpcfci3u4pt4v9omch6.apps.googleusercontent.com',
    iosBundleId: 'com.icv1.app',
  );
}
